### ISSUE TITLE
Cross-compile Linux->Windows fails on latest commit: "undefined: securityAttributes"

### ISSUE THREAD

**Issue by rfay** [Microsoft/go-winio#52]
On the current HEAD I see this on a cross-compile hosted on Linux (golang 1.8.1) and targeted at Windows (CGO_ENABLED=0; GOOS=windows)

```
go install -installsuffix static -ldflags ' -extldflags -static'  ./cmd/... ./pkg/...
# github.com/drud/ddev/vendor/github.com/Microsoft/go-winio
vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:142: undefined: securityAttributes
vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:151: undefined: securityAttributes
vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:164: undefined: securityAttributes
vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:173: undefined: securityAttributes
```

This problem appears to have been introduced in https://github.com/Microsoft/go-winio/pull/48, as it happens on 13736c32520969a64987228c21c138a4cfdb3720 and does not happen before that PR (compiles fine with f3b1913901892ada21d52d0cffe1d4c7080d36b7)

**Comment by darrenstahlmsft** [comment]
Huh... I really have no clue how that commit broke it, as I didn't change the definition at all. The only thing that I can think of is that it was optimized out due to using a pointer as the only reference (just a guess, don't have time to dig into this right this moment)?

Unfortunately I don't have a Linux machine handy, and we don't see this on Windows. I can fire up a VM when I can spare some time and attempt to repro.

**Comment by darrenstahlmsft** [comment]
This seemed to be some weird artifact of that commit needing CGO. It works on current HEAD now that CGO is no longer required as of https://github.com/Microsoft/go-winio/commit/d311c76e775b5092c023569caacdbb4e569c3243

```
# go version
go version go1.8.1 linux/amd64
# export GOOS="windows"
# go env
GOARCH="amd64"
GOBIN=""
GOEXE=".exe"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="windows"
GOPATH="/home/darst/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build980419667=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="0"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
# git log -n 1
commit d311c76e775b5092c023569caacdbb4e569c3243
Merge: 518e6eb de045f7
Author: John Starks <jostarks@microsoft.com>
Date:   Mon May 8 14:01:43 2017 -0700

    Merge pull request #51 from darrenstahlmsft/NoCGO

    Remove cgo as a dependency added by #49
# go build -ldflags '-extldflags -static'
```

Closing, as it is fixed. Let me know if it's not fixed for you.

**Comment by rfay** [comment]
I confirm that this compiles on current HEAD, thanks!
